language: node_js
node_js:
  - "18.13.0"
notifications:
  email: false

cache:
  directories:
  - node_modules

install:
  - npm install

before_script:
  - npm run lint
  - npm run stylelint-fix-sass

script:
  - npm start
  # - npm test

after_success:
  - npm run build  # Збірка продакшен версії додатку

branches:
  only:
    - main

notifications:
  email:
    on_success: never
    on_failure: always